GET http://192.168.100.50:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2FybG9zIiwiaWF0IjoxNjQwNzU5NDkyfQ.2wqWwuoA9DAf-YkeesTQZGCBU7bTwZQ2nr5_IqtZ35g
###

POST http://192.168.100.50:3000/register
Content-Type: application/json

{
    "username": "Carlos",
    "password": "654321"
}

###

POST http://192.168.100.50:3000/login
Content-Type: application/json

{
    "username": "Carlos",
    "password": "654321"
}

